---
- name: Tear down libvirt networks
  hosts: pn50
  gather_facts: false
  environment:
    LIBVIRT_DEFAULT_URI: "{{ libvirt_uri | default('qemu:///system') }}"

  vars:
    _networks:
      - "{{ (libvirt_network_nat | default({})).name | default('default') }}"
      - "{{ (libvirt_network_airgap | default({})).name | default('airgap') }}"

  tasks:
    - name: Get list of existing libvirt networks
      community.libvirt.virt_net:
        command: list_nets
      register: _existing_nets

    - name: Destroy libvirt networks
      community.libvirt.virt_net:
        command: destroy
        name: "{{ item }}"
      loop: "{{ _networks }}"
      when: item in _existing_nets.list_nets
      failed_when: false

    - name: Undefine libvirt networks
      community.libvirt.virt_net:
        command: undefine
        name: "{{ item }}"
      loop: "{{ _networks }}"
      when: item in _existing_nets.list_nets
      failed_when: false
