---
- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest  # noqa: package-latest
  register: _dnf_update
  retries: 3
  delay: 10
  until: _dnf_update is succeeded

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - dnsmasq
      - tree
      - tmux
      - vim
      - podman
      - jq
    state: present
