---
# -- OCP versions --
ocp_version: "stable-4.21"
ocp_release_version: "4.21.0"
ocp_mirror_base_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp"

# -- Paths --
ocp_mirror_dir: "/opt/ocp-mirror"
ocp_webroot: "/opt/ocp-webroot"
mirror_registry_dir: "/opt/mirror-registry"

# -- Quay mirror registry --
mirror_registry_version: "1.3.11"
quay_hostname: "bastion.{{ cluster_name }}.{{ dns_domain }}"
quay_port: 8443
quay_init_user: "init"

# -- Pull secret --
pull_secret_path: "~/.pullsecret.json"

# -- Operators to mirror --
ocp_operators: []

# -- Additional images to mirror --
ocp_additional_images: []
