---
all:
  children:
    hypervisor:
      hosts:
        pn50:
          ansible_user: jrickard
          ansible_become: true
    bastion_hosts:
      hosts:
        bastion:
          ansible_host: 192.168.127.5
          ansible_user: ansible
          ansible_become: true
