---
all:
  children:
    hypervisor:
      hosts:
        pn50:
          ansible_user: jrickard
          ansible_become: true
    bastion_hosts:
      hosts:
        bastion:
          ansible_host: 192.168.0.147
          ansible_user: fedora
          ansible_become: true
